### ISSUE TITLE
Data server down?

### ISSUE THREAD

**Issue by liquight** [flatironinstitute/spikeforest2#26]
Is the data server up? I'm using the spike forest python API which was working until yesterday. Today it seems it is not able to connect to the server. To reproduce, if I try the example given in the README, it gets stuck at 

`recording = AutoRecordingExtractor(recording_path, download=False)`

and after waiting a long time I get these messages:

`Retrying http request in 0.2 sec: http://132.249.245.245:24342/check/sha1/5863072e3fdef93186f8b977b7f3021c9b29cb48?channel=public&signature=d5d52291187eeb38d45cb6db03ca1333accb11ad`

Seems like the server is not responding. Its the same case if I try to access any other dataset. Can you please check?

**Comment by magland** [comment]
Thanks for the report, seems like that server is inaccessible, I have made an inquiry about this and will respond soon.

**Comment by magland** [comment]
@breadnbeer, I think it should be up now, let me know if it works.

**Comment by liquight** [comment]
The server is still not reachable. Tried from two different machines on different networks - a university network and a home network.

**Comment by magland** [comment]
Could you show the error message? We updated new IPs in the config (which
is pulled down from github at runtime), and I wonder if the correct IP is
being retrieved.

**Comment by liquight** [comment]
I get these messages:
`Retrying http request in 0.2 sec: http://132.249.245.245:24342/check/sha1/ee5214337b2e01910a92c3613a4b8ad4be4dc476?channel=public&signature=7ec2cd38f04e02cb1d9b2e29b9cb01dc343a7ec5`

**Comment by magland** [comment]
Thanks, that's the old IP -- my mistake, there was one more place I needed
to update it. Please try again in >=120 seconds.
J

**Comment by liquight** [comment]
It is still trying the same server.
`Retrying http request in 0.2 sec: http://132.249.245.245:24342/check/sha1/ee5214337b2e01910a92c3613a4b8ad4be4dc476?channel=public&signature=7ec2cd38f04e02cb1d9b2e29b9cb01dc343a7ec5`

I don't suppose I need to download and reinstall spikeforest2, do I?

**Comment by magland** [comment]
Oops again, please try now.

(and if it still doesn't work, delete the ~/.kachery directory and try again)

**Comment by liquight** [comment]
It's working now. Thanks a lot!  I didn't have to delete ~/.kachery or do anything else.

The project is great! It's been very useful. Thanks.

**Comment by magland** [comment]
Awesome, glad it's working! You may be interested in this project which is sort of the next phase of data sharing, etc:
https://github.com/flatironinstitute/neuropixels-data-sep-2020
