### ISSUE TITLE
Problem accessing datasets using python

### ISSUE THREAD

**Issue by liquight** [flatironinstitute/spikeforest2#30]
I'm getting these errors when accessing datasets using the python API. 

`Warning: Problem checking for file: Unable to open url: http://132.249.245.246:24342/check/sha1/ec98194e93cee0255bd778b8003ebd0f121e4a3b?channel=public&signature=b21dd59ca85f3561bf4c5323ed161c868523aef8`
`Exception: Unable to find file: sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/001_synth/raw.mda`

Can you please check. It was working fine few days ago, I think this started yesterday.

**Comment by liquight** [comment]
Any update on this? Seems to be an issue with the server itself.

**Comment by shijiegu** [comment]
I have exactly the same issue too!

**Comment by shijiegu** [comment]
Using the paths in the ReadMe:

`recording_path = 'sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/010_synth'
sorting_true_path = 'sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/010_synth/firings_true.mda'

recording = AutoRecordingExtractor(recording_path, download=False)
sorting_true = AutoSortingExtractor(sorting_true_path)`

Gives the following error:

> Exception                                 Traceback (most recent call last)
> <ipython-input-7-5410e267180e> in <module>()
>       9 sorting_true_path = 'sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/010_synth/firings_true.mda'
>      10 
> ---> 11 recording = AutoRecordingExtractor(recording_path, download=False)
>      12 sorting_true = AutoSortingExtractor(sorting_true_path)
>      13 
> 
> /Users/shijiegu/Documents/Second-Year/EE290/Project/spikeforest2/spikeforest2_utils/autoextractors/autorecordingextractor.py in __init__(self, arg, download)
>      57                     self._recording = MdaRecordingExtractor(recording_directory=path, download=download)
>      58                 else:
> ---> 59                     raise Exception('Unable to initialize recording extractor. Unable to determine format of recording: {}'.format(path))
>      60         self.copy_channel_properties(recording=self._recording)
>      61 
> 
> Exception: Unable to initialize recording extractor. Unable to determine format of recording: sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/010_synth

**Comment by magland** [comment]
Hi @breadnbeer and @shijiegu.

Yes, we had a change of IP address on the server. I have updated the configuration. Please try again and let me know if it is working now.

**Comment by liquight** [comment]
Yes it is working now. Thank you very much @magland !

**Comment by magland** [comment]
Glad that's working, and thanks for the report.

**Comment by shijiegu** [comment]
It is working. Next time could you please put a note on the ReadMe or website?

**Comment by NebulaWang** [comment]
Hi, I met this problem again. Any suggestions for me to fix this bug? Thanks a lot!
![image](https://user-images.githubusercontent.com/40286575/168440695-96c8303d-807e-4de5-87f7-63852da5c86e.png)
