### ISSUE TITLE
Unable to access datasets

### ISSUE THREAD

**Issue by liquight** [flatironinstitute/spikeforest2#34]
I am unable to access the datasets using the python API. I am getting the following errors when running the code in the readme.

```
Retrying http request in 0.2 sec: http://kachery.flatironinstitute.org/neuro1/check/sha1/ee5214337b2e01910a92c3613a4b8ad4be4dc476?channel=public&signature=7ec2cd38f04e02cb1d9b2e29b9cb01dc343a7ec5
Retrying http request in 0.5 sec: http://kachery.flatironinstitute.org/neuro1/check/sha1/ee5214337b2e01910a92c3613a4b8ad4be4dc476?channel=public&signature=7ec2cd38f04e02cb1d9b2e29b9cb01dc343a7ec5
Warning: Problem checking for file: Unable to open url: http://kachery.flatironinstitute.org/neuro1/check/sha1/ee5214337b2e01910a92c3613a4b8ad4be4dc476?channel=public&signature=7ec2cd38f04e02cb1d9b2e29b9cb01dc343a7ec5
```

Can you please check. Thanks.

**Comment by magland** [comment]
Sorry our servers are down for maintenance. I think they will be back up in a few days.
But there's a new mechanism for obtaining the spikeforest datasets:
https://github.com/flatironinstitute/spikeforest/blob/main/doc/download-spikeforest-data.md

**Comment by liquight** [comment]
Hi @magland. The new mechanism works, but it uses UDP ports which are really bothersome to work with ssh tunnels on cluster nodes. We run data processing code on clusters and connecting to the kachery daemon running on one node from any other cluster node is a problem. I'm trying to convert UPD to TCP on these ports and use the ssh tunnels, but it's not working as of now. Either I start a kachery daemon on each node where the code is run, but I don't think it's the right way to go about. Any suggestions?

**Comment by magland** [comment]
we are working on a cluster as well, and the nodes connect to the same kachery daemon, and also share the kachery storage directory. I wonder how similar our environments are. Why don't you send an email and we can find a time to chat.

**Comment by magland** [comment]
For anyone else reading this thread. The issue was that the docs for kachery-p2p needs some clarification. The --port flag when starting the daemon does not represent the listen port for the client connecting to the daemon, but rather represents a port for inter-node communication. You must use the KACHERY_P2P_API_PORT for both the client and for the running daemon.

@breadnbeer

**Comment by liquight** [comment]
Thank you @magland. It is working now.
To clarify, I set the variable KACHERY_P2P_API_PORT before starting the daemon as well as for the client. I tunnel only this particular port between different nodes so that the python API on other nodes can connect to the daemon.
