### ISSUE TITLE
spykingcircus example fails for me

### ISSUE THREAD

**Issue by yarikoptic** [flatironinstitute/spikeforest2#4]
Tried https://github.com/magland/spikeforest2/blob/master/examples/example_spykingcircus.sh example (while in a branch for #3).  FWIW I did not have docker image locally
```shell
(git)lena:~/proj/spikodrome/spikeforest2[bf-mandatory-recording]
$> sf-sort -a spykingcircus -r sha1://961f4a641af64dded4821610189f808f0192de4d/SYNTH_MEAREC_TETRODE/synth_mearec_tetrode_noise10_K10_C4/002_synth.json -o sorting_sc.json
===== Hither: running spykingcircus in container: docker://magland/sf-spykingcircus:0.8.6
unknown flag: --gpus
See 'docker run --help'.
Traceback (most recent call last):
  File "/home/yoh/proj/spikodrome/spikeforest2/venvs/dev3/bin/sf-sort", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/yoh/proj/spikodrome/spikeforest2/bin/sf-sort", line 44, in <module>
    main()
  File "/home/yoh/proj/spikodrome/spikeforest2/bin/sf-sort", line 26, in main
    sorting_path = sort(algorithm=algorithm, recording_path=recording_path)
  File "/home/yoh/proj/spikodrome/spikeforest2/bin/sf-sort", line 36, in sort
    result = sorter.run(recording=recording_path, sorting_out=hither.File())
  File "/home/yoh/proj/spikodrome/spikeforest2/hither/_core.py", line 180, in run
    local_modules=local_modules
  File "/home/yoh/proj/spikodrome/spikeforest2/hither/_run_function_in_container.py", line 188, in run_function_in_container
    raise Exception('Non-zero exit code ({}) running {} in container {}'.format(retcode, name, container))
Exception: Non-zero exit code (125) running spykingcircus in container docker://magland/sf-spykingcircus:0.8.6
```

BTW, spotted above, not sure if you intend to keep compatibility with some older pythons, but if >= 3.6 you might love to start using implicit `.formatt()`ing via [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) -- makes code more readable and concise.

**Comment by magland** [comment]
What version of docker do you have? The docs say >=19.

The issue is the --gpu flag. This is a bit mysterious to me. I had to install https://github.com/NVIDIA/nvidia-docker on my host system -- but it's a bit mysterious to me. This will need to be included in the installation docs.

**Comment by yarikoptic** [comment]
oh, that is probably from docker itself (might be worth adding a check for the version.  I could introduce [our helper from datalad](https://github.com/datalad/datalad/blob/master/datalad/support/external_versions.py) so you could ask `if external_versions['cmd:docker'] < '19':.`  I have 
```
$> docker --version
Docker version 18.09.9, build 039a7df
```
upgrade to 19.03.4+dfsg2-2

**Comment by magland** [comment]
be sure not to miss my comment of 1 minute ago.

**Comment by yarikoptic** [comment]
yeap... indeed -- would need that beast (`nvidia-docker`). Just FYI with regular 19.x docker I get

```
===== Hither: running spykingcircus in container: docker://magland/sf-spykingcircus:0.8.6
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
Traceback (most recent call last):
...
```
that is why singularity in the longer run generally would be better IMHO for users on linux, although would also need more recent (iirc some `3.0.`) version with `--nv` flag.
Which sorter is non-GPU based so I could try without reinstalling docker ATM?

**Comment by magland** [comment]
(a) It already works with singularity. Just set HITHER_USE_SINGULARITY=TRUE environment variable. You need to have singularity >=3.3 I believe (I have 3.5). Yes, it uses the --nv flag.

(b) the only gpu sorters now are ks2 and irc. sc and ms4 do not use gpu. so spykingcircus would have worked. We just need to expose the gpu option in hither. Maybe I'll do that now.

**Comment by magland** [comment]
I just pushed a version that only uses --gpus (--nv) flags for the gpu sorters. Therefore you my try either spykingcircus or mountainsort4 without needing to install nvidia-docker
